#define IDI_ICON 100
#define IDD_ABOUT 151
#define IDC_ABOUT_DATE 152

#define IDM_MENU 200
#define MENU_FILE_OPEN_MODEL 307
#define MENU_FILE_MERGE_MODEL 308
#define MENU_FILE_OPEN_ANIMATION 309
#define MENU_FILE_EXPORT_MODEL 301
#define MENU_FILE_EXPORT_TEXTURES 302
#define MENU_FILE_EXPORT_SHADERS 303
#define MENU_FILE_REIMPORT_SHADERS 304
#define MENU_FILE_REGENERATE_SHADERS 305
#define MENU_FILE_EXIT 306

#define MENU_HELP_ABOUT 401

#define MENU_DEBUG_SECTIONINFO 501
